name: 'fitb_dbt_utils'
version: '1.0.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]
config-version: 2

dispatch:
  - macro_namespace: dbt
    search_order: ['my_project_name', 'fitb_dbt_utils', 'dbt_project_evaluator', 'dbt']
  - macro_namespace: dbt_utils
    search_order: ['my_project_name', 'fitb_dbt_utils', 'dbt_utils']

target-path: ["target"]
clean-targets: ["target", "dbt_packages", "packages"]
macro-paths: ["macros"]
log-path: ["data_project_assets/logs"]
